POST http://localhost:5000/api/users HTTP/1.1
 Content-Type: application/json

{
  "firstName": "Nata2",
  "lastName": "Yakov2",
  "email": "nat2yyyda@gmail.com",
  "password": "qwerty106783",
  "birthday" : "1983-10-14",
  "gender": "female"
}