POST http://localhost:5000/api/user HTTP/1.1
 Content-Type: application/json

 {
  "firstName": "Nataliia9",
  "lastName": "Yakovenko9",
  "email": "Natal56*@gmail.com",
  "password": "Qwerty125*",
  "birthday" : "1983-10-14",
  "gender": "female"
 }